# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
