# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20180611_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users', to_field='username'),
        ),
    ]
