# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180612_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
